version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - foyer-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/c/Users/arram/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker:ro  # Clé de la solution !
    user: root  # Nécessaire temporairement
    networks:
      - foyer-net
    depends_on:
      - sonarqube

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8082:8081"
    networks:
      - foyer-net
    volumes:
      - nexus-data:/nexus-data

  app:
    build: .
    image: arrami/foyer-app:latest
    container_name: spring-app
    ports:
      - "8081:8080"
    networks:
      - foyer-net
    depends_on:
      - sonarqube

networks:
  foyer-net:
    driver: bridge

volumes:
  jenkins_data:
  nexus-data:
