version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - foyer-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # 👉 Utilise ton Dockerfile personnalisé
    container_name: jenkins
    privileged: true                  # 👉 Nécessaire pour le socket Docker
    user: root                        # 👉 Nécessaire pour utiliser Docker dans Jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👉 Accès au Docker de l’hôte
    networks:
      - foyer-net
    depends_on:
      - sonarqube

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8082:8081"
    networks:
      - foyer-net
    volumes:
      - nexus-data:/nexus-data

  app:
    build: .
    image: arrami/foyer-app:latest
    container_name: spring-app
    ports:
      - "8081:8080"
    networks:
      - foyer-net
    depends_on:
      - sonarqube

networks:
  foyer-net:
    driver: bridge

volumes:
  jenkins_data:
  nexus-data:
