version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - foyer-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - foyer-net
    depends_on:
      - sonarqube

  app:
    build: .
    image: arrami/foyer-app:latest
    container_name: spring-app
    ports:
      - "8081:8080"  # Changé de 8080 à 8081 pour éviter les conflits
    networks:
      - foyer-net
    depends_on:
      - sonarqube

networks:
  foyer-net:
    driver: bridge

volumes:
  jenkins_data: