version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - foyer-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true 
    user: root  # ✅ permet d'exécuter docker dans Jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ accès à Docker hôte
    networks:
      - foyer-net
    depends_on:
      - sonarqube
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io docker-compose &&
        /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8082:8081"
    networks:
      - foyer-net
    volumes:
      - nexus-data:/nexus-data

  app:
    build: .
    image: tchala/foyer-app:latest
    container_name: spring-app
    ports:
      - "8081:8080"
    networks:
      - foyer-net
    depends_on:
      - sonarqube

networks:
  foyer-net:
    driver: bridge

volumes:
  jenkins_data:
  nexus-data:
