pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "arrami/foyer-app:latest"
        SONAR_HOST = "sonarqube"
    }

    tools {
        maven 'Maven3.9.6'
        // jdk 'JDK17' // décommente si configuré
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/HEDI121/Pi.git'
            }
        }

        stage('Build & Compile') {
            steps {
                dir('Foyer2425-main') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Tests') {
            steps {
                dir('Foyer2425-main') {
                    sh 'mvn test'
                }
            }
        }

        stage('Analyse SonarQube') {
            steps {
                withSonarQubeEnv("SonarLocal") {
                    dir('Foyer2425-main') {
                        sh "mvn sonar:sonar -Dsonar.host.url=http://${SONAR_HOST}:9000"
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Foyer2425-main') {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Push Docker') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('Foyer2425-main') {
                    sh 'docker-compose down || true'
                    sh 'docker-compose up -d --build'
                }
            }
        }
    }
}
